# Generated by Django 4.2.6 on 2023-12-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studnetassignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudnetAssignment',
            new_name='StudentAssignment',
        ),
    ]
