# Generated by Django 4.2.6 on 2023-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification_alter_student_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_read_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifread_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Notification Created Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
    ]
